### ISSUE TITLE
Memory limit exceptions with large files

### ISSUE THREAD

**Issue by JPvRiel** [nerik/google-timeline-to-csv#2]
WIth a large input json file I get:

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

Obviously this quick/useful utility started with the intention of parsing daily files parsing all the content in memory I assume. Find for daily (usually small in size), but then got extended to full history files.

Probably not worth it to try refactor into a IO stream-like process, but instead, may in the readme suggest people need to increase the default node heap size, e.g. using `node --max-old-space-size=8192 index.js  ...`

**Comment by nerik** [comment]
https://github.com/nerik/google-timeline-to-csv/commit/201a20cf40fe5595df5d389d5ac3f15c89de53f6
